[versions]

compose-activity = "1.10.1"

kotlin = "2.1.0"
android = "8.6.1"
compose = "1.7.0"

sdk-min = "26"
sdk-compile = "35"
sdk-target = "35"

[libraries]

compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }

[plugins]

kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android = { id = "com.android.application", version.ref = "android" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }